### ISSUE TITLE
Has developmet stopped?

### ISSUE THREAD

**Issue by roboserg** [getindata/kedro-vertexai#130]
Last commit seems to be from 1 year ago, which makes it risky to use this plug-in in production, without an ongoing maintenance.

**Comment by marrrcin** [comment]
Hi!
We're still maintaining the plugin :) At it's current state, it's fairly stable and we're using it in multiple projects without major problems.
We're going to release a new version with some updates related to support for Kedro 0.19.x soon.

**Comment by marrrcin** [comment]
Btw, last release was on Aug 23, 2023 - where did you get the "last commit from 1 year ago" from? https://github.com/getindata/kedro-vertexai/releases/tag/0.9.1

**Comment by marrrcin** [comment]
No response from the original author. Closing, as plugin **has active and ongoing development** 🙂
