### ISSUE TITLE
Dependencies issues pydantic

### ISSUE THREAD

**Issue by adrienpl** [getindata/kedro-vertexai#166]
Hello,

With kedro-vertexai 0.11.0, we can't use the plugin with kedro-viz or other pydantic dependent package since kedro-vertexai is locked to pydantic <2.0.0 and kedro-viz for kedro 19 > need pydantic >= 2.0.0

Is it possible to upgrade pydantic dependencie ?

Regards,

**Comment by Lasica** [comment]
Hi,
yes, I think it should be priority in the next update to bump pydantic

**Comment by adrienpl** [comment]
Do you have an idea when we will be able to use kedro-vertexai with update version of pydantic ?

**Comment by Lasica** [comment]
probably in few weeks when I have time to sit down to it, or when someone does a PR with it to speed it up

**Comment by adrienpl** [comment]
Thanks a lot ! Your work is amazing !
