### ISSUE TITLE
Params of type list not accepted in VertexAI

### ISSUE THREAD

**Issue by em-pe** [getindata/kedro-vertexai#23]
When trying to use parameters of type list vertexAI pipeline fails with the error.

INPUT in `params.yml`:
```
signature_columns:
  - email
  - created_at
  - creation_country
  - has_company_name
  - partner_id
  - account_type
  - followers_count
  - posts_count
  - is_private
  - is_verified
  - risk_level
```

Generated step that fails:
![Screenshot 2022-03-29 at 13 05 13](https://user-images.githubusercontent.com/31856783/160598343-30fabb0f-1884-4486-bd6a-6dbc5cc14478.png)

Error:
![Screenshot 2022-03-29 at 13 08 27](https://user-images.githubusercontent.com/31856783/160598537-add704b5-a9c6-4917-b1a4-f8af72a2715d.png)

**Comment by marrrcin** [comment]
Same as https://github.com/getindata/kedro-kubeflow/issues/60

**Comment by szczeles** [comment]
We use this setup: https://github.com/getindata/kedro-kubeflow/pull/90 in Kubeflow and it works nice with both lists and dicts.
