### ISSUE TITLE
Templated configuration does not work with globals

### ISSUE THREAD

**Issue by PiotrrMenclewicz** [getindata/kedro-vertexai#28]
When trying to use a global parameter saved in `globals.yml`, the following error is returned:

```ValueError: Failed to format pattern '${data_root_path}': no config value found, no default provided```

After updating `hooks.py` and adding a variable `KEDRO_VERTEXAI_DISABLE_CONFIG_HOOK=true`, global parameters start to be recognized.

**Comment by marrrcin** [comment]
We're missing `globals_pattern="*globals.yml",` in EnvTemplatedConfigLoader.

**Comment by em-pe** [comment]
Sounds like a quick fix that we can try to address this week.
