### ISSUE TITLE
Investigate overriding default MemoryDataSet

### ISSUE THREAD

**Issue by marrrcin** [getindata/kedro-vertexai#8]
Right now the plug-in requires all intermediate datasets to be stored in GCS, which forces the pipeline authors to remember that all intermediate datasets need to be explicitly defined in the data catalog.
Consider overriding the `create_default_data_set` in the `ThreadRunner` https://github.com/kedro-org/kedro/blob/74fbd752b6bf77c409f016ed73e60a4ea38d6a95/kedro/runner/thread_runner.py#L51 or find other extension point to make the use of intermediate datasets transparent to the users (we could store them in GCS, as we already have paths to bucket and unique run id in the plugin).

**Comment by em-pe** [comment]
We need to clarify the details and make it environment based as this may not be an optimal setup for a local runs, just the pipelines one.
